import os, subprocess, sys, pytest, re
import cfdvv

_THIS = os.path.dirname(os.path.abspath(__file__))
TEST_DIR = os.path.join(_THIS, "integration_data")
CFDVV_DIR = os.path.dirname(cfdvv.__file__)
CASE = os.path.join(CFDVV_DIR, "cases", "verification", "incompressible", "poiseuille-2d")
_PROJ = os.path.dirname(os.path.dirname(CFDVV_DIR))  # tools/ dir for cwd


def run_cfdvv(*args):
    result = subprocess.run(
        [sys.executable, "-m", "cfdvv.cli"] + list(args),
        capture_output=True, text=True, timeout=30, cwd=_PROJ
    )
    return result.stdout + result.stderr


def _read_golden(name):
    with open(os.path.join(TEST_DIR, name), "r", encoding="utf-8") as f:
        return f.read()


def _strip_paths(text):
    """Normalize machine-specific paths in CLI output for cross-platform comparison."""
    # Replace the Result: line with a placeholder (paths differ per machine)
    text = re.sub(r'Result:.*\n', 'Result: <PATH>\n', text)
    return text


def _strip_report_html(html: str) -> str:
    """Normalize machine-specific content in HTML reports for golden comparison."""
    html = re.sub(
        r'(?<=<dt>Result \(user\)</dt><dd>).*?(?=</dd>)',
        '<RESULT_PATH>', html,
    )
    html = re.sub(
        r'(?<=<dt>Generated</dt><dd>)\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?=</dd>)',
        '<TIMESTAMP>', html,
    )
    html = re.sub(
        r'(?<=Generated by <strong>cfdvv</strong> )v\d+\.\d+\.\d+(?= —)',
        '<VERSION>', html,
    )
    lines = html.splitlines(keepends=True)
    result_lines = []
    seen_result_user = False
    for line in lines:
        if '<dt>Result (user)</dt>' in line:
            seen_result_user = True
        if seen_result_user and '<dt>Reference</dt>' in line:
            line = re.sub(r'(?<=<dd>).*?(?=</dd>)', '<REF_PATH>', line)
            seen_result_user = False
        result_lines.append(line)
    return ''.join(result_lines)


def _has_matplotlib():
    try:
        import matplotlib  # noqa: F401
        return True
    except ImportError:
        return False


class TestGoodSolution:
    def test_good_compare_zero(self):
        result_csv = os.path.join(TEST_DIR, "good_poiseuille.csv")
        output = run_cfdvv("compare", CASE, "-r", result_csv, "--no-plot")
        golden = _read_golden("golden_good.txt")
        assert _strip_paths(output) == _strip_paths(golden), "CLI output changed"

    def test_good_report_golden(self):
        """Golden-file test: 'cfdvv report' output is stable (no plots)."""
        import tempfile
        report_path = os.path.join(tempfile.gettempdir(), "test_report.html")
        result_csv = os.path.join(TEST_DIR, "good_poiseuille.csv")
        run_cfdvv("report", CASE, "-r", result_csv, "-o", report_path)
        with open(report_path, "r", encoding="utf-8") as f:
            generated = f.read()
        golden = _read_golden("golden_report.html")
        assert _strip_report_html(generated) == golden, "HTML report output changed"

    def test_good_report_has_required_sections(self):
        """Report always contains metadata and comparison table (no matplotlib needed)."""
        import tempfile
        report_path = os.path.join(tempfile.gettempdir(), "test_report.html")
        result_csv = os.path.join(TEST_DIR, "good_poiseuille.csv")
        run_cfdvv("report", CASE, "-r", result_csv, "-o", report_path)
        with open(report_path, "r", encoding="utf-8") as f:
            result = f.read()
        assert "poiseuille-2d" in result
        assert "Plane Poiseuille" in result
        assert "Comparison Results" in result
        assert "Parameters" in result
        assert "Result (user)" in result
        assert "Reference" in result

    @pytest.mark.skipif(not _has_matplotlib(), reason="matplotlib not installed")
    def test_good_report_with_plots(self):
        """Report includes embedded plots when matplotlib is available."""
        import tempfile
        report_path = os.path.join(tempfile.gettempdir(), "test_report.html")
        result_csv = os.path.join(TEST_DIR, "good_poiseuille.csv")
        run_cfdvv("report", CASE, "-r", result_csv, "-o", report_path)
        with open(report_path, "r", encoding="utf-8") as f:
            result = f.read()
        assert "Comparison Plot" in result, "report should contain embedded plot sections"
        assert result.find("Comparison Plot") > result.find("Comparison Results"), \
            "plot section must be after comparison results"


class TestBadSolution:
    def test_bad_compare_detects_error(self):
        result_csv = os.path.join(TEST_DIR, "bad_poiseuille.csv")
        output = run_cfdvv("compare", CASE, "-r", result_csv, "--no-plot")
        golden = _read_golden("golden_bad.txt")
        assert _strip_paths(output) == _strip_paths(golden), "CLI output changed"


class TestFewPoints:
    def test_few_points_stable(self):
        result_csv = os.path.join(TEST_DIR, "few_points.csv")
        output = run_cfdvv("compare", CASE, "-r", result_csv, "--no-plot")
        golden = _read_golden("golden_few.txt")
        assert _strip_paths(output) == _strip_paths(golden), "CLI output changed"


class TestExampleOutput:
    def test_example_output_stable(self):
        output = run_cfdvv("example-output", CASE)
        golden = _read_golden("golden_example.txt")
        assert _strip_paths(output) == _strip_paths(golden), "CLI output changed"
