#!/bin/bash
# OpenFOAM Poiseuille-2D Verification Case
# Usage: ./Allrun
# Requires: OpenFOAM sourced
set -e
blockMesh
simpleFoam
postProcess -func sampleDict -latestTime
echo "Done. Compare with: cfdvv compare . -r reference/analytical/solution.csv"
