name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install build
      - run: python -m build tools/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tools/dist/
